# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6db7f0ca6bfb046999780f06747c89892086b0650a62d2e9cabe751e27eabb28ed11df75584ee0ea31e2bd86bb26d3b6c6b4c7198fe7e8fa9c8c15ba1eb6f2f3

test:
  secret_key_base: 36de58a45f89cbb1a416d5f95ec954aaa9b8a45a10589565a42e2dcb4b52b97a70d49e9536b501e6cf51ac911525164d6d1ee6c15c24d9a748b5799f6f747301

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
